[package]
name = "yee-signer"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
schnorrkel = "0.8.5"
jni = "0.16.0"

[dev-dependencies]
hex = "0.3.2"
